apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fdt

resources:
  - ../base
  - order-service.yaml
  - driver-service.yaml
  - tracking-service.yaml
  - notification-service.yaml
  - ingress.yaml
